-- Seed table 'avatars' with an additional set of avatars.
INSERT INTO avatars (id, name)
VALUES (89, 'beetroot'),
       (90, 'bread'),
       (91, 'cabbage'),
       (92, 'cake'),
       (93, 'cake piece'),
       (94, 'carrot'),
       (95, 'mistletoe'),
       (96, 'chocolate'),
       (97, 'cocktail'),
       (98, 'cookie'),
       (99, 'corn'),
       (100, 'doughnut'),
       (101, 'ice cream'),
       (102, 'kiwi'),
       (103, 'mango'),
       (104, 'milkshake'),
       (105, 'mushroom'),
       (106, 'peach'),
       (107, 'peanuts'),
       (108, 'pear'),
       (109, 'pie'),
       (110, 'pizza'),
       (111, 'popcorn'),
       (112, 'pumpkin'),
       (113, 'coffee cup'),
       (114, 'tomato'),
       (115, 'vanilla flower');